-- =====================================================
-- Datenbank-Setup für Übung 3
-- Dieses Skript erstellt alle benötigten Tabellen und fügt Testdaten ein
-- =====================================================

-- WICHTIG: Führen Sie dieses Skript in Ihrer Oracle-Datenbank aus
-- Stellen Sie sicher, dass Sie die richtigen Berechtigungen haben

PROMPT =====================================================
PROMPT Schritt 1: Alte Tabellen löschen (falls vorhanden)
PROMPT =====================================================

-- Drop constraints first (in reverse order of dependencies)
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE ZAHLART DROP CONSTRAINT FK_ZAHLART_ZAHLT_MIT_NUTZER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE ZAHLART DROP CONSTRAINT FK_ZAHLART_GEHORT_ZU_ZAHLTYP';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE RECHNUNG DROP CONSTRAINT FK_RECHNUNG_RELATIONS_RECHNUNN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE RECHNUNG DROP CONSTRAINT FK_RECHNUNG_AN_NUTZER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE POSITION DROP CONSTRAINT FK_POSITION_POSITION2_RECHNUNG';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE POSITION DROP CONSTRAINT FK_POSITION_POSITION_MAUTERHE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE MAUTKATEGORIE DROP CONSTRAINT FK_MAUTKATE_BESTEHT_A_SCHADSTO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE MAUTERHEBUNG DROP CONSTRAINT FK_MAUTERHE_MIT_MAUTABSC';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE MAUTERHEBUNG DROP CONSTRAINT FK_MAUTERHE_DURCH_FAHRZEUG';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE MAUTERHEBUNG DROP CONSTRAINT FK_MAUTERHE_BERECHNET_MAUTKATE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE FAHRZEUGGERAT DROP CONSTRAINT FK_FAHRZEUG_RELATIONS_FAHRZEUG';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE FAHRZEUG DROP CONSTRAINT FK_FAHRZEUG_GEHOERT_NUTZER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE FAHRZEUG DROP CONSTRAINT FK_FAHRZEUG_FAEHRT_MI_SCHADSTO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE BUCHUNG DROP CONSTRAINT FK_BUCHUNG_HAT_BUCHUNGS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE BUCHUNG DROP CONSTRAINT FK_BUCHUNG_BEZIEHT_S_MAUTKATE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE BUCHUNG DROP CONSTRAINT FK_BUCHUNG_BEINHALTE_MAUTABSC';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop tables
DECLARE
    table_count NUMBER;
BEGIN
    FOR t IN (SELECT table_name FROM user_tables 
              WHERE table_name IN ('ZAHLART', 'ZAHLTYP', 'RECHNUNG', 'RECHNUNNGSSTATUS', 
                                   'POSITION', 'MAUTERHEBUNG', 'MAUTKATEGORIE', 'MAUTABSCHNITT',
                                   'FAHRZEUGGERAT', 'FAHRZEUG', 'BUCHUNG', 'BUCHUNGSTATUS',
                                   'SCHADSTOFFKLASSE', 'NUTZER'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
        DBMS_OUTPUT.PUT_LINE('Tabelle ' || t.table_name || ' gelöscht');
    END LOOP;
END;
/

PROMPT =====================================================
PROMPT Schritt 2: Führen Sie nun die create.sql aus
PROMPT =====================================================
PROMPT @db/maut/create.sql

PROMPT =====================================================
PROMPT Schritt 3: Führen Sie die Insert-Skripte aus
PROMPT =====================================================
PROMPT @db/maut/insert/NUTZER.sql
PROMPT @db/maut/insert/SCHADSTOFFKLASSE.sql
PROMPT @db/maut/insert/MAUTKATEGORIE.sql
PROMPT @db/maut/insert/FAHRZEUG.sql
PROMPT @db/maut/insert/FAHRZEUGGERAT.sql
PROMPT @db/maut/insert/MAUTABSCHNITT.sql
PROMPT @db/maut/insert/BUCHUNGSTATUS.sql
PROMPT @db/maut/insert/BUCHUNG.sql
PROMPT @db/maut/insert/MAUTERHEBUNG.sql
PROMPT @db/maut/insert/RECHNUNNGSSTATUS.sql
PROMPT @db/maut/insert/RECHNUNG.sql
PROMPT @db/maut/insert/ZAHLTYP.sql
PROMPT @db/maut/insert/ZAHLART.sql
PROMPT @db/maut/insert/POSITION.sql

PROMPT =====================================================
PROMPT Setup abgeschlossen!
PROMPT Sie können nun die Tests ausführen.
PROMPT =====================================================
